# Generated by Django 3.0.6 on 2020-05-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20200523_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klasses', to='students.Programme'),
        ),
    ]
