# Generated by Django 3.0.6 on 2020-05-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200522_1422'),
        ('students', '0004_auto_20200523_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='klasses', to='core.School'),
        ),
    ]
