# Generated by Django 3.0.6 on 2020-05-21 05:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_time_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=core.models.recipe_image_file_path),
            preserve_default=False,
        ),
    ]
